### ISSUE TITLE
RuntimeError: Library libcublas.so.12 is not found or cannot be loaded

### ISSUE THREAD

**Issue by abhiabhijit** [tekeburak/podcast-summarizer#1]
Hi, Im following the readme to run the app and got struck at this error in modal app. Did you face any similar error ? If yes , can u please help me resolve it?

```
Podcast Episode downloaded
/usr/local/lib/python3.11/site-packages/pyannote/audio/core/io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
Load the Whisper model
No language specified, language will be first be detected for each audio file (increases inference time).
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.2.3. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint .cache/torch/whisperx-vad-segmentation.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.3.0+cu118. Bad things might happen unless you revert torch to 1.x.
Starting podcast transcription
Traceback (most recent call last):
  File "/pkg/modal/_container_io_manager.py", line 488, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 134, in run_input
    res = imp_fun.fun(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/podcast_backend.py", line 87, in get_transcribe_podcast
    result = model.transcribe(audio, batch_size=batch_size)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/whisperx/asr.py", line 194, in transcribe
    language = language or self.detect_language(audio)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/whisperx/asr.py", line 252, in detect_language
    encoder_output = self.model.encode(segment)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/whisperx/asr.py", line 86, in encode
    return self.model.encode(features, to_cpu=to_cpu)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Library libcublas.so.12 is not found or cannot be loaded
```

**Comment by tekeburak** [comment]
The error message actually contains a description of the error. It's related to Cuda and PyTorch version (1.10.0+cu102). If it is solved, please write the solution here.
